### ISSUE TITLE
Unable to run python code from a remote client system

### ISSUE THREAD

**Issue by porous999** [zaratsian/pyspark#1]
One small thing which did not make sense with me is the need to set the environment variable _SPARK_HOME_ to run a spark code. My spark server endpoint could be running in a server in any part of the world, and this does not make sense to have a SPARK_HOME set even in the client system.
I believe I should be able to connect to any spark endpoint (given I have access to the same), similar to how it works in Scala or other langauges.

**Comment by zaratsian** [comment]
Hi porous999, depending on your environment, you will not need to set SPARK_HOME at all. For example, within the Hortonworks Distribution, Spark, Yarn, Hadoop/HDFS, and may other services are already pre-installed and ready to go. This is typically done through Yarn, although you could connect directly to a Spark server, Mesos, or everything can be ran locally.  

See this link for configuring Spark jobs and connecting to the appropriate master (such as Yarn): http://spark.apache.org/docs/current/submitting-applications.html#master-urls

**Comment by porous999** [comment]
Hi @zaratsian, I believe I couldn't make it clearer the first time.... Allow me to rephrase it...

While executing the script, I might be in a different environment, and I might not have any info regarding how a (remote) cluster is set up... May be different user, or system, there is no way of knowing what the _SPARK_HOME_ is... And while execution of a PySpark code, it searches for the _SPARK_HOME_ in the environment variables, or we need to explicitly mention it in the script. This setting up of a server side environment variable in the client side code doesn't seem correct. Would love if you could share some info on the same.
